import { Router, type IRouter } from "express";
import healthRouter from "./health";
import diagnosticsRouter from "./diagnostics";
import securityRouter from "./security";
import securityDefenseRouter from "./security-defense";
import providerSovereigntyRouter from "./provider-sovereignty";
import memoryRouter from "./memory";
import reasoningRouter from "./reasoning";
import swarmRouter from "./swarm";
import ingestionRouter from "./ingestion";
import inventionsRouter from "./inventions";
import councilRouter from "./council";
import councilMeetingRouter from "./council-meeting";
import latticeHardwareRouter from "./lattice-hardware";
import conversationsRouter from "./conversations";
import worldRouter from "./world";
import forumRouter from "./forum";
import sovereignDataRouter from "./sovereign-data";
import benchmarkAuditRouter from "./benchmark-audit";
import fleetSynapseRouter from "./fleet-synapse";
import colonialLanguageRouter from "./colonial-language";
import meshRouter from "./mesh";
import evaluationRouter from "./evaluation";
import routingRouter from "./routing";
import ontologyRouter from "./ontology";
import improvementRouter from "./improvement";
import roadmapRouter from "./roadmap";
import sovereigntyScoreRouter from "./sovereignty-score";
import systemMetricsRouter from "./system-metrics";
import tesseraBibleRouter from "./tessera-bible";
import theoremLabRouter from "./theorem-lab";

const router: IRouter = Router();

router.use(healthRouter);
router.use(diagnosticsRouter);
router.use(securityRouter);
router.use(securityDefenseRouter);
router.use(providerSovereigntyRouter);
router.use(memoryRouter);
router.use(reasoningRouter);
router.use(swarmRouter);
router.use(ingestionRouter);
router.use(inventionsRouter);
router.use(councilRouter);
router.use(councilMeetingRouter);
router.use(latticeHardwareRouter);
router.use(conversationsRouter);
router.use(worldRouter);
router.use(forumRouter);
router.use(sovereignDataRouter);
router.use(benchmarkAuditRouter);
router.use(fleetSynapseRouter);
router.use(colonialLanguageRouter);
router.use(meshRouter);
router.use(evaluationRouter);
router.use(routingRouter);
router.use(ontologyRouter);
router.use(improvementRouter);
router.use(roadmapRouter);
router.use(sovereigntyScoreRouter);
router.use(systemMetricsRouter);
router.use(tesseraBibleRouter);
router.use(theoremLabRouter);

export default router;
